name: "ğŸ—ï¸ Build and Test ğŸ§ª"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "support/*" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v3

      - name: âœ… Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: ğŸ“¦ Cache Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/**/content
            !~/.nuget/packages/**/contentFiles
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: â¬‡ï¸ Restore Dependencies
        run: dotnet restore

      - name: ğŸ—ï¸ Build
        run: dotnet build -c Release --no-restore

      - name: ğŸ§ª Test
        run: dotnet test -c Release --no-build --verbosity normal